"""empty message

Revision ID: 683ce3b27349
Revises: cbc606232a0b
Create Date: 2020-06-10 21:14:22.436259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683ce3b27349'
down_revision = 'cbc606232a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    # ### end Alembic commands ###
