"""empty message

Revision ID: 591c08989de3
Revises: ce2a89976172
Create Date: 2020-06-05 01:14:52.896100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591c08989de3'
down_revision = 'ce2a89976172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('session_token', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'telegram_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
